import { Metadata } from "next";

import { LoginForm } from "@/components/auth/login-form";

export const metadata: Metadata = {
  title: "Connexion",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return <LoginForm />;
}
