import { Metadata } from "next";

import { RegisterForm } from "@/components/auth/register-form-patient";

export const metadata: Metadata = {
  title: "Inscription - Patient",
  description: "Generated by create next app",
};

export default function RegisterPatientPage() {
  return <RegisterForm />;
}
