import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "./(protected)/_components/navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <nav className="flex items-center justify-between p-4 bg-blue-800 text-white">
              <div className="flex items-center space-x-4">
                <h1 className="text-xl font-semibold">Auth</h1>
              </div>
              <div className="space-x-4">
                <Link href="/">Accueil</Link>
                <Link href="/practitioner">Êtes vous practicien ?</Link>
              </div>
            </nav>
          </header>
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
