import { RegisterForm } from "@/components/auth/register-form-pro";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Inscription - Pro",
  description: "Generated by create next app",
};

export default function RegisterProPage() {
  return <RegisterForm />;
}
